modLoader="javafml"
loaderVersion="[40,)"
license="Code: MIT, Textures: Some Restrictions Apply"
issueTrackerURL="https://github.com/malcolmriley/minecraft-paintings/issues"

[[mods]]
modId="paragon_paintings"
version="${file.jarVersion}"
displayName="Foreboding Paintings"
logoFile="logo.png"
credits="The_Paragon"
authors="Malcolm Riley"
description='''
A collection of mildly-unsettling AI-generated paintings supposedly based on the works of Francisco Goya.
'''

[[dependencies.paragon_paintings]]
	modId="forge"
	mandatory=true
	versionRange="[40.1,)"
	ordering="NONE"
	side="BOTH"
